// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI-fY5eFakDLeUB50t87hfcudTue42T7c',
    appId: '1:217217520914:web:184110c3b648dd44470fcb',
    messagingSenderId: '217217520914',
    projectId: 'thecareercompany-3c299',
    authDomain: 'thecareercompany-3c299.firebaseapp.com',
    storageBucket: 'thecareercompany-3c299.appspot.com',
    measurementId: 'G-F2RXX3DCZ3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6y1GN0kKmokqwBL6Zt0y5oxssr29fXt4',
    appId: '1:217217520914:ios:6c63292a58586aaa470fcb',
    messagingSenderId: '217217520914',
    projectId: 'thecareercompany-3c299',
    storageBucket: 'thecareercompany-3c299.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI-fY5eFakDLeUB50t87hfcudTue42T7c',
    appId: '1:217217520914:web:f222effcaf64abce470fcb',
    messagingSenderId: '217217520914',
    projectId: 'thecareercompany-3c299',
    authDomain: 'thecareercompany-3c299.firebaseapp.com',
    storageBucket: 'thecareercompany-3c299.appspot.com',
    measurementId: 'G-3Y9Y5D8FKS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6y1GN0kKmokqwBL6Zt0y5oxssr29fXt4',
    appId: '1:217217520914:ios:6c63292a58586aaa470fcb',
    messagingSenderId: '217217520914',
    projectId: 'thecareercompany-3c299',
    storageBucket: 'thecareercompany-3c299.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx7pMFHz8uhl2r4f3GCQzkSfqjGTBDr3k',
    appId: '1:217217520914:android:6ab28ff10bb424fb470fcb',
    messagingSenderId: '217217520914',
    projectId: 'thecareercompany-3c299',
    storageBucket: 'thecareercompany-3c299.appspot.com',
  );

}